# Generated by Django 2.0.9 on 2019-01-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_date',
        ),
    ]
