# Generated by Django 2.0.9 on 2019-01-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0002_remove_profile_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
